### ISSUE TITLE
Cannot make requests: "Remote end closed connection without response"

### ISSUE THREAD

**Issue by thesadru** [AnimeThemes/animethemes-server#53] opened 2020-11-01 18:53 UTC
Since the server update, requesting anything no longer works. The remote end **always** closes without response. This is not only for videos but for the entire site.
I have tried asking on discord, but was told that using javascript works, therefore I think it's just an error with how the requests are handled. My case is with python.
Using this test code we can test this issue:
```py
from urllib.request import urlopen
url = "https://animethemes.moe/video/BlendS-OP1-BD1080.webm"
r = urlopen(url)
```
[There's also a remote link on repl.it, if you don't have python installed](https://repl.it/repls/NewFuzzyApplicationstack#main.py)
As you can see the connection always closes.

**Comment by ProWeebDev** [comment] 2020-11-02 01:01
Works as intended.

**Comment by paranarimasu** [comment] 2020-11-02 22:12
Your request is getting caught in our nginx blacklist. These lists were compiled from prior abuse. Our service does not target scripted access to our repository files and we will not be adjusting these lists in the short-term. This may be adjusted at a later date to accommodate a whitelist of locations; we probably don't want to drop requests to api endpoints, for example.

Since this is out of scope for this project - nginx configuration isn't maintained here - I will be closing this issue.

**Closed by paranarimasu** 2020-11-02 22:12 UTC

**Comment by paranarimasu** [comment] 2020-11-03 17:58
Hello, after reviewing this mention and related changesets, I feel the need to state more explicitly that we consider this project abusive. Please do not expect any accommodation from us or this project going forward.
